'use server';

/**
 * @fileOverview Provides a summarized report of detected zero-day threats, generated by the AI engine.
 *
 * - zeroDayThreatSummary - A function that returns the summarized report of zero-day threats.
 * - ZeroDayThreatSummaryInput - The input type for the zeroDayThreatSummary function.
 * - ZeroDayThreatSummaryOutput - The return type for the zeroDayThreatSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ZeroDayThreatSummaryInputSchema = z.object({
  timePeriod: z
    .string()
    .default('last 24 hours')
    .describe('The time period for which to summarize zero-day threats.'),
  logData: z.string().describe('Log data containing potential zero-day threat information.'),
});
export type ZeroDayThreatSummaryInput = z.infer<typeof ZeroDayThreatSummaryInputSchema>;

const ZeroDayThreatSummaryOutputSchema = z.object({
  summary: z.string().describe('A summary of the detected zero-day threats.'),
});
export type ZeroDayThreatSummaryOutput = z.infer<typeof ZeroDayThreatSummaryOutputSchema>;

export async function zeroDayThreatSummary(input: ZeroDayThreatSummaryInput): Promise<ZeroDayThreatSummaryOutput> {
  return zeroDayThreatSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'zeroDayThreatSummaryPrompt',
  input: {schema: ZeroDayThreatSummaryInputSchema},
  output: {schema: ZeroDayThreatSummaryOutputSchema},
  prompt: `You are a security expert analyzing system logs for zero-day threats.
  Based on the following log data from the {{{timePeriod}}}, provide a concise summary of any detected zero-day threats, including their nature and severity.  If there are no zero-day threats evident in the log data, indicate that no threats were detected.

  Log Data:
  {{logData}}`,
});

const zeroDayThreatSummaryFlow = ai.defineFlow(
  {
    name: 'zeroDayThreatSummaryFlow',
    inputSchema: ZeroDayThreatSummaryInputSchema,
    outputSchema: ZeroDayThreatSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
